leoafarias/fvm

lib/commands/config.dart
lib/constants.dart
lib/exceptions.dart
lib/fvm.dart
lib/utils/config_utils.dart
lib/utils/flutter_tools.dart

Modify the directory of the stored flutter sdk

---

.gitignore
lib/commands/flutter.dart
lib/commands/list.dart
lib/fvm.dart
lib/utils/helpers.dart

Resolved #18 .
---
An additional modification, in order to verify whether the fvm of the parent directory was found.
Use fvm list will like next.
```bash
$ fvm list
beta
dev(current)
```

Recursive query fvm.

---

lib/commands/install.dart
lib/utils/flutter_tools.dart

Improved error handling

---

README.md
lib/commands/use.dart
lib/constants.dart
lib/utils/flutter_tools.dart
test/fvm_test.dart

Flag to link a Flutter version to use globally

---

lib/commands/list.dart
lib/utils/helpers.dart

Added global version indicator

---

lib/constants.dart

Honor FVM_HOME environment variable when declared

---

CHANGELOG.md
coverage_badge.svg
lib/exceptions.dart
lib/flutter/flutter_releases.dart
lib/flutter/flutter_tools.dart
lib/src/version.dart
pubspec.yaml

Added notice and env var for blocked storage_url

---

lib/commands/use.dart
pubspec.yaml

Try `fvm use` or `fvm use --global`

Purposal  fuzzy search

---

pubspec.yaml

Updated process_run dependency

---

packages/cli/lib/src/local_versions/local_versions_tools.dart

Thank you for providing an awesome tool!
I found a typo while using `fvm` so I fixed it.
Could you please confirm when you have time?

Fixed a typo in `local_versions_tools.dart`

---

packages/cli/lib/src/commands/install_command.dart

fix RangeError when installing pinned version (no version arg)

---

packages/cli/lib/src/commands/flutter_command.dart
packages/cli/lib/src/flutter_tools/flutter_tools.dart

More strict lineMode switch

---

packages/cli/README.md
packages/cli/lib/src/commands/install_command.dart
packages/cli/lib/src/commands/remove_command.dart
packages/cli/lib/src/flutter_tools/flutter_helpers.dart
packages/cli/pubspec.yaml

Added symlink on install behavior without version

---

packages/cli/lib/src/commands/use_command.dart
packages/cli/lib/src/flutter_project/flutter_project.repo.dart
packages/cli/lib/src/workflows/use_version.workflow.dart
packages/cli/test/flutter_project_test.dart

Changed ancestor lookup logic

---

packages/cli/CHANGELOG.md
packages/cli/lib/src/flutter_tools/flutter_helpers.dart
packages/cli/lib/src/flutter_tools/flutter_tools.dart
packages/cli/lib/src/version.dart
packages/cli/pubspec.yaml
packages/cli/test/utils/flutter_tools_tes_t.dart

Addresses https://github.com/invertase/melos/issues/21

Better support for flutter proxy on third party tools

---

packages/cli/pubspec.yaml
packages/cli/tool/grind.dart

cli_pkg update

---

packages/app/lib/app_shell.dart
packages/app/lib/components/atoms/cache_date_display.dart
packages/app/lib/components/atoms/console.dart
packages/app/lib/components/atoms/instruction_view.dart
packages/app/lib/components/molecules/advanced_info_tile.dart
packages/app/lib/components/molecules/delete_dialog.dart
packages/app/lib/components/molecules/reference_info_tile.dart
packages/app/lib/components/organisms/search_bar.dart
packages/app/lib/providers/flutter_releases.provider.dart
packages/app/lib/providers/fvm_console_provider.dart
packages/app/lib/providers/projects_provider.dart
packages/app/lib/screens/projects.screen.dart
packages/app/lib/utils/prune_versions.dart
packages/app/pubspec.yaml
packages/app/test/widget_test.dart

I fixed the issue using the pub.dev dependency of `file_chooser`.
I also fixed a crash on the ExploreScreen
Then I also resolved some warnings.
closes  #210

Fix macOS errors

---

.docker/Dockerfile

Hi guys,
I created a very-first version of a docker image for a ready-to-use fvm environment for based-docker CI. 
I didn't edit the Github actions to build the image and to publish it on Docker Hub, because I have no clue about the release workflow.
If you give me more info about it I can give you my support!
Closes #205 
Cheers! :beers:

First version of Dockerfile

---

packages/cli/lib/src/commands/flutter_command.dart
packages/cli/lib/src/commands/install_command.dart
packages/cli/lib/src/commands/use_command.dart
packages/cli/lib/src/flutter_project/flutter_project.repo.dart
packages/cli/lib/src/flutter_project/fvm_config_repo.dart
packages/cli/lib/src/workflows/install_version.workflow.dart

Ensures flutter is installed

---

lib/src/commands/use_command.dart
lib/src/version.dart
pubspec.yaml

Issue with cli_dialog on install

---

lib/src/services/cache_service.dart
test/commands_test.dart

Fix isGlobalConfigured()

---

CHANGELOG.md
lib/src/models/valid_version_model.dart
lib/src/services/flutter_tools.dart
lib/src/utils/helpers.dart
lib/src/workflows/ensure_cache.workflow.dart

Allows custom versions

---

CHANGELOG.md
lib/src/version.dart
lib/src/workflows/ensure_cache.workflow.dart
pubspec.yaml

Fixes update link

---

CHANGELOG.md
lib/src/models/cache_version_model.dart
lib/src/utils/commands.dart
lib/src/utils/helpers.dart
lib/src/version.dart
pubspec.yaml

Passes bin path instead of exec

---

CHANGELOG.md
lib/src/commands/flutter_command.dart
lib/src/utils/commands.dart
lib/src/version.dart
pubspec.yaml

Preamble as a trace only

---

CHANGELOG.md
lib/src/commands/dart_command.dart

Only display dart version on --verbose

---

lib/constants.dart
lib/src/utils/commands.dart
lib/src/utils/guards.dart

Command detach check

---

lib/constants.dart
lib/src/utils/guards.dart
lib/src/utils/helpers.dart

Clean up logic for should detach

---

CHANGELOG.md
lib/src/models/config_model.dart

Correct type when reading config

---

website/docs/guides/faq.md
website/docusaurus.config.js
website/i18n/es/code.json
website/i18n/es/docusaurus-plugin-content-docs/current.json
website/i18n/es/docusaurus-plugin-content-docs/current/advanced/_category_.json
website/i18n/es/docusaurus-plugin-content-docs/current/advanced/custom_version.md
website/i18n/es/docusaurus-plugin-content-docs/current/advanced/install_revision.md
website/i18n/es/docusaurus-plugin-content-docs/current/advanced/release_multiple_channels.md
website/i18n/es/docusaurus-plugin-content-docs/current/getting_started/_category_.json
website/i18n/es/docusaurus-plugin-content-docs/current/getting_started/configuration.mdx
website/i18n/es/docusaurus-plugin-content-docs/current/getting_started/installation.mdx
website/i18n/es/docusaurus-plugin-content-docs/current/getting_started/overview.md
website/i18n/es/docusaurus-plugin-content-docs/current/guides/_category_.json
website/i18n/es/docusaurus-plugin-content-docs/current/guides/basic_commands.md
website/i18n/es/docusaurus-plugin-content-docs/current/guides/faq.md
website/i18n/es/docusaurus-plugin-content-docs/current/guides/global_configuration.md
website/i18n/es/docusaurus-plugin-content-docs/current/guides/project_flavors.md
website/i18n/es/docusaurus-plugin-content-docs/current/guides/running_flutter.md
website/i18n/es/docusaurus-plugin-content-docs/current/tools.md
website/i18n/es/docusaurus-theme-classic/footer.json
website/i18n/es/docusaurus-theme-classic/navbar.json
website/src/components/HomepageFeatures.tsx
website/src/pages/index.tsx

This PR will:
- add Spanish translation of the .mdx files.
- add"es" locale to **website/docusaurus.config.js**.
- fix minor issues I've found in the English docs during the translation.

Add Spanish Translation

---

CHANGELOG.md
lib/src/commands/dart_command.dart
lib/src/commands/destroy_command.dart
lib/src/commands/exec_command.dart
lib/src/models/cache_version_model.dart
lib/src/models/config_model.dart
lib/src/runner.dart
lib/src/utils/commands.dart
lib/src/utils/helpers.dart

Implementing exec command

---

.github/workflows/deploy_docker.yml

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
Fixes #461

Execute Docker Release workflows on release/published

---

CHANGELOG.md
README.md
lib/src/commands/dart_command.dart
lib/src/commands/exec_command.dart
lib/src/commands/flutter_command.dart
lib/src/commands/global_command.dart
lib/src/commands/remove_command.dart
lib/src/commands/use_command.dart
lib/src/runner.dart
lib/src/services/cache_service.dart
lib/src/services/context.dart
lib/src/services/releases_service/current_release_parser.dart
lib/src/utils/commands.dart
lib/src/utils/console_utils.dart
lib/src/utils/fvm_client.dart
lib/src/utils/messages.dart
test/cache_version_test.dart
test/commands_test.dart
test/services/cache_service_test.dart
website/docs/getting_started/installation.mdx
website/docs/guides/global_configuration.md

This will deprecate `global` command as described here on #469

Global command deprecation

---

lib/src/utils/logger.dart

Fixes https://github.com/fluttertools/fvm/issues/483

Fix crash when running in Azure DevOps pipeline

---

website/docs/tools.md

This just adds a short mention that Codemagic now has builtin support for FVM config files and pointers to further information in the Codemagic docs.

Document Codemagic support for FVM config files

---

CHANGELOG.md
README.md

Hello there! @leoafarias I've been using FVM for quite some time now and it's been a great helper. Thus, I've decided to contribute to the documentation improvements (having little time available to pursue deeper challenges on open-source projects at the moment).
What I've done in this PR - improved the docs' (`README.md` and `CHANGELOG.md`) Markdown formatting, writing style and writing consistency.
Let me know your thoughts. I'm open to any kind of feedback. Thanks!

chore: improve docs formatting and style (README.md and CHANGELOG.md)

---

lib/src/workflows/use_version.workflow.dart

Closes #598
Does not ask for confirmation if its running on VSCode if vscode is not detected.

Do not ask to setup vscode

---

lib/src/workflows/ensure_cache.workflow.dart

Accepts longer commit hash

---

lib/src/workflows/use_version.workflow.dart
pubspec.lock
pubspec.yaml

Changed comment clean up

---

lib/src/workflows/use_version.workflow.dart

Change flutter project check

---

lib/src/services/releases_service/releases_client.dart
lib/src/workflows/ensure_cache.workflow.dart
lib/src/workflows/use_version.workflow.dart

Added fallback for version validation

---

lib/src/utils/commands.dart

Added fallback to global version

---

docs/pages/documentation/guides/basic-commands.md
docs/pages/documentation/guides/global-configuration.mdx
lib/src/commands/global_command.dart
lib/src/services/global_version_service.dart

Unlink global version

---

lib/src/models/config_model.dart
lib/src/utils/deprecation_util.dart
tool/homebrew.dart

Update dependencies and fix deprecation warnings

---

docs/pages/documentation/getting-started/configuration.mdx

Hi,
Thank you for creating a wonderful project.
I have a minor concern; there appears to be a mistake in the .gitignore code block.
Please feel free to close it if there are any issues.
before | after
--- | ---

Fix configuration doc

---

lib/src/utils/parsers/git_clone_update_printer.dart

Handle failure of parsing progress

---

docs/pages/documentation/getting-started/faq.md

Copied from https://codingislove.com/unable-to-find-git-path-flutter

Add Git not Found on PATH to Windows FAQ

---

.github/workflows/deploy_homebrew.yml
tool/grind.dart

Adds versioned formulae

---

docs/pages/documentation/guides/basic-commands.md

Added destroy command

---

lib/src/commands/global_command.dart

Fixes https://github.com/leoafarias/fvm/issues/711

Add force flag to global command

---

lib/src/utils/parsers/git_clone_update_printer.dart
pubspec.lock
pubspec.yaml

Better logging on mirror creation

Better error logging on mirror creation

---

lib/src/utils/parsers/git_clone_update_printer.dart

Handle printer exception

---

.github/workflows/deploy_docker.yml

Should fix failing [Docker deployment job](https://github.com/leoafarias/fvm/actions/runs/8362373127/job/22892804344) as well as #621

Add tags for Docker deployment

---

scripts/install.sh

Added sudo to the symbolic link creation for proper permissions
Defined the missing Red color for error messages
Ensured the creation of FVM_DIR_BIN directory before moving files
Improved overall script readability and maintainability

fix: Corrected variable name from FMV_DIR_BIN to FVM_DIR_BIN

---

.github/workflows/install-script-test.yml

This pull request updates the script verification process in the `.github/workflows/install-script-test.yml` file. The changes shift the focus from comparing the local and public versions of the `install.sh` script to ensuring the internal consistency of the script by checking for essential functions and features.
* Updated the verification process to check for the presence of critical functions (`tildify()`, `success()`, `error()`) in `scripts/install.sh`.
* Added checks for OS and architecture detection (`uname -s` and `uname -m`) in `scripts/install.sh`.
* Removed the comparison between the local and public versions of `install.sh` and replaced it with internal consistency checks.
* Included validation for a root user check to ensure the script is not run as root.

chore: improve workflow for install test

---

.github/workflows/install-script-test.yml
docs/public/install.sh
scripts/install.sh
test/install_script_improvements_test.dart

This PR provides comprehensive improvements to the `scripts/install.sh` file following DRY, YAGNI, and KISS principles, along with enhanced security and robust testing infrastructure.
- **DRY**: Created `update_shell_config()` helper function, eliminating ~50 lines of duplicated shell configuration logic
- **YAGNI**: Removed speculative architecture support (armv7l, ia32, riscv64) with no documented user demand  
- **KISS**: Simplified architecture detection to x64/arm64 only, streamlined shell configuration logic
- ✅ Added input validation for version parameters with regex `[^a-zA-Z0-9._-]`
- ✅ Enhanced download validation with `--fail --show-error` curl flags
- ✅ Added file type validation using `file` command to verify gzip archives
- ✅ Added binary existence validation after …

feat: enhance install script with comprehensive improvements and testing

---

lib/src/commands/integration_test_command.dart
lib/src/services/flutter_service.dart
test/services/flutter_service_test.dart
test/services/git_clone_fallback_test.dart

Implements a robust Git clone fallback mechanism that gracefully handles `--reference` flag failures and falls back to normal clone operations. This addresses issues where Git clone operations using the `--reference` flag for GitHub mirror optimization fail and produce unclear error messages.
- **Added `_cloneWithFallback()` method** that attempts clone with `--reference` first, then falls back to normal clone
- **Added `isReferenceError()` method** to detect reference-specific Git errors with comprehensive pattern matching
- **Added `_cleanupPartialClone()` method** to handle corrupted/partial clone state cleanup
- **Integrated fallback mechanism** into existing `install()` workflow
- Detects reference repository errors: `reference repository not found`, `unable to read reference`, etc. …

feat: implement Git clone fallback mechanism for --reference failures

---

.github/workflows/test.yml

- Remove sequential dependencies in GitHub Actions workflow to enable parallel execution
- Allow macOS/Windows tests to run in parallel with Ubuntu tests instead of waiting
- Reduce integration test dependencies to only wait for main Ubuntu test
- **Before:** Sequential execution ~31 minutes total
- **After:** Parallel execution ~23 minutes total  
- **Expected improvement:** 25-30% faster CI pipeline
- Commented out `needs: test` dependency for cross-platform tests
- Changed integration test dependency from `[test, test-os]` to `test` only
- Zero functional changes - only removes artificial waiting
- This PR will validate the performance improvement by triggering the optimized workflow
- Monitor actual runtime vs predicted ~23 minutes
- Easy rollback if any issues arise (just restore 2 …

perf: optimize CI pipeline for parallel execution
