leoafarias/fvm

lib/commands/flutter.dart
Added `--debug` and `--release` flags in order to get these commands working:
```bash
> fvm flutter build apk --debug
> fvm flutter build apk --release
> fvm flutter build ios --debug
> fvm flutter build ios --release
```
=> Added debug and release flags for the flutter command

lib/fvm.dart, lib/utils/flutter_tools.dart, lib/utils/helpers.dart
thanks for nice tools.
when i use fvm in windows, i found some errors.
we should use 'flutter.bat' to execute command and uri is different with mac os.
I have test them in windows and mac, it seems to work fine both.
=> fix errors for windows platform

.gitignore, CHANGELOG.md, README.md, lib/utils/flutter_tools.dart, lib/utils/helpers.dart, test/utils/helpers_test.dart
Flutter uses a new versioning scheme starting with version 1.17.0. Tags don't have a ' v' prefix anymore.
This commit ensures that versions with and without prefix are handled correctly.
=> #51 Add Flutter 1.17+ support

lib/fvm.dart
Most `Exception` subtypes have a message but they are not required to have the field. Neither do `Error` subtypes. Most Dart exceptions/errors return their message when calling `toString()`.
See first stacktrace in https://github.com/leoafarias/fvm/issues/106
=> Fix _CastError due to some Dart core errors not having a message field

lib/src/commands/config_command.dart, lib/src/utils/commands.dart
Having `fvm flutter …` invoke `dart` instead of `flutter` in this specific case only doesn't sound like intended behavior.
Also includes a fix for a build error introduced in 61ae729.
=> Forward global version `flutter` proxy calls to `flutter` executable

.docker/alpine/Dockerfile, .github/workflows/cli_deploy_docker.yml
Fixes #251 As described in the issue, the docker container that uses `google/dart` has many security notices that get flagged by Twistlock and other open source security vulnerability scanners. This can cause problems using the image in enterprise environments. Using alpine allows to use `fvm` without causing problems with Twistlock.
I used [trivy](https://github.com/aquasecurity/trivy) to run analysis on the new alpine image which shows no vulnerabilities. 
1. Created a Dockerfile in `./docker/alpine/Dockerfile` directory which installs necessary dependencies on alpine 3:13 and installs `fvm` using binary releases. 
2. Added a GitHub Action workflow to build and push the alpine image under `fvm-alpine` tag
=> Add alpine 3.13 container image

lib/src/commands/doctor_command.dart, lib/src/commands/flutter_command.dart, lib/src/services/config_service.dart, lib/src/utils/helpers.dart, pubspec.yaml, tool/grind.dart
=> Fixed race condition for link creation

website/docusaurus.config.js
Link points to docusaurus instead of FVM.
=> Update link to Github

.github/workflows/deploy_homebrew.yml, .github/workflows/release.yml, .github/workflows/test.yml
`pub` standalone is deprecated and should be replaced with `dart pub`.
=> ci: use `dart pub` instead of `pub` standalone, because it's deprecated

CHANGELOG.md, lib/src/models/cache_version_model.dart
=> Support for old dart path

README.md
The screenshot image location changed recently in the Sidekick repo, this PR fixes the screenshot link to point to the new address.
=> Fix Sidekick screenshot image

lib/src/commands/use_command.dart
- Update `fvm use` to use the Flutter version defined in the config file if the version is not provided as an argument.
- I didn't see any existing tests for the `install` command on this similar feature, and I'm not sure how to add one for this. But happy to give it a go if you can share how to write tests for this.
- Close #397
=> Update use command to use config if no version is provided

website/docs/getting_started/configuration.mdx
It wasn't clear in the docs that the user should run `fvm use` inside the projects folder producing the situation described in #411.
=> docs - explicit fvm use in vscode

lib/src/commands/install_command.dart, lib/src/commands/list_command.dart
- This change provides a new way to call `install` and `list` commands in FVM, now users can use `'i'` as a short-hand command while trying to install a new version and use `'ls'` as short-hand command while trying to list installed versions.
`fvm i X.X.X` or `fvm install X.X.X`
`fvm ls` or `fvm list`
This PR closes #502
=> feat: implement short hand commands for install and list options

lib/src/commands/config_command.dart
Adds a space after the period in `fvm config --cache-path` usage instructions.
Currently:
```
-c, --cache-path         Set the path which FVM will cache the version.Priority over FVM_HOME.
```
With this fix:
```
-c, --cache-path         Set the path which FVM will cache the version. Priority over FVM_HOME.
```
=> Add space after period in fvm config help

website/package.json, website/yarn.lock
@leoafarias  This is an attempt to fix the failure of the documentation deployment action: https://github.com/fluttertools/fvm/actions/runs/4713405556/jobs/8359082936
According to the [comment on the docusaurus issue](https://github.com/facebook/docusaurus/issues/5778#issuecomment-1012045850) a combination of using the latest version of docusaurus plus regenerating the yarn lock file to ensure version 5.5 or newer of webpack is used should fix the underlying issue, more details about which are on [this SO thread](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported).
Unfortunately I can't easily test this myself as the Github action for deploying the docs is obviously set to only run on merges into `main`
=> update docusaurus version to fix ssl algo error

lib/src/services/config_repository.dart
The Flutter project reports a warning to users who replace the standard GitHub location of Flutter with their own. They also provide an environment variable (`FLUTTER_GIT_URL`) which can be set by the user to indicate that this is intentional.
FVM provides a similar feature to override the GIT location from which the Flutter install will be cloned, and it is implemented as the command-line parameter `--flutterUrl`.
Defaulting to using the environment variable defined by Flutter as the value of `flutterUrl`, provides most corporations that host their own repository with a seamless use of the `fvm` tool without requiring all developers to include the `--flutterUrl` parameter manually.
=> feature: allowing FLUTTER_GIT_URL to be the default value of flutterUrl

lib/src/models/config_model.dart, lib/src/models/project_model.dart, lib/src/services/config_repository.dart, lib/src/services/project_service.dart
Generates legacy fvm_config.json file to better support tools that need to migrate
=> Added legacy config

CHANGELOG.md, lib/src/commands/use_command.dart, lib/src/version.g.dart, lib/src/workflows/ensure_cache.workflow.dart, pubspec.yaml
When running fvm use with a custom Flutter version or running with the force command, FVM still tries to correctly handle version mismatching. However, it is expected that the installed version should be used as this is the custom installed folder or is forced by adding the force command.
This should fix issue https://github.com/leoafarias/fvm/issues/653
=> Add skipping version mismatch handling when using force or running with a custom fvm version.

lib/src/workflows/ensure_cache.workflow.dart
When installing the flutter version from `fvm use <version|flavor>`, there is a prompt 
This PR adds the missing check before the prompt to force the installation.
Fixes: #579
=> feat: add force check before install prompt

docs/pages/documentation/guides/basic-commands.md, lib/src/commands/install_command.dart, lib/src/commands/use_command.dart, lib/src/workflows/use_version.workflow.dart
In large projects, getting the dependencies may require more than just a `pub get` in the root dir.
This PR adds an optional flag to get the current project dependencies. The default value is `true` to not disrupt current usage. The flag is negatable to _not_ get the dependencies
=> feat: add deps flag to optional get project dependencies after switch

docs/pages/documentation/advanced/_meta.json
I noticed that `Install Revievision` page cannot be opened on the WebSite and it doesn't seem to exist in the docs, so let's remove it to avoid confusion.
=> docs: remove entry to non existing 'Install Revision' page

docs/pages/documentation/getting-started/faq.md
The links on the screenshot lead to 404 at the moment. The current PR fixes that.
=> docs: fix links in FAQ

.docker/Dockerfile
We should target the `dart:latest` Docker image, as this is now the official Dart image and (as the title suggests) the previous google/dart image is no longer available.
=> Update Dockerfile due to discontinuation of google/dart image

lib/src/utils/helpers.dart
assignVersionWeight function should remove `custom_` before parse version else `fvm dart` will not working because
```
bool get hasOldBinPath {
return compareSemver(assignVersionWeight(version), '1.17.5') <= 0;
}
```
Fixes https://github.com/leoafarias/fvm/pull/654#issuecomment-2005697264
=> Fix assignVersionWeight do not handle custom version

docs/pages/documentation/guides/monorepo.md, lib/src/services/project_service.dart
=> Remove requirement for pubspec, added logging

lib/src/utils/console_utils.dart
Because of the lack of the trailing space, the option appeared like `Select a version:1`. Now it looks like this: `Select a version: 1`
=> fix(global): adds trailing space to version prompt

lib/src/commands/list_command.dart
Create a new column to show the current local version if the project has a local version configured. 
In a project with a custom version configured : 
In a project without configuration files present: 
I'm open to write some test but I did't find a way.
=> Issue #723 : New column Local in command List

docs/pages/documentation/guides/basic-commands.mdx, docs/pages/documentation/guides/project-flavors.md, lib/src/commands/flavor_command.dart, lib/src/runner.dart
This pull request introduces a new command, fvm flavor, to the Flutter Version Management (FVM) tool. The flavor command allows developers to execute Flutter commands using a specific Flutter SDK version defined by a project flavor.
Issue #575
=> Feat #575 - Add fvm flavor command

docs/pages/documentation/guides/running-flutter.mdx
- This PR addresses command rerouting issue https://github.com/leoafarias/fvm/issues/719.
>I think we can add this as a tip in this section here:
@leoafarias  I'm unsure if I fully understood the primitive "tip", but I assumed it was an ` info callout`. It looks a little weird to have an info block that long unless its just me. But happy to hear your thoughts.
=> add documentation for command rerouting

lib/src/runner.dart
Hey there, first of all: Thank you very much for your work with fvm! I really really love the tool and if I have improvements for the future, I am going to contribute and try to help that way!
I was facing a very annoying and draining issue that occurred after reinstalling my laptop, which was that I could not generate protobuffers for dart anymore.
I was pulling my hair out trying to understand, what was happening. And now I found the issue, you can see it in the changes of this PR.
I am wondering if you had any special use case why this extra newline was needed. If you ask me, FVM should not alter the output of at least the dart calls, as to not break compatibility with tools that are developed against plain dart, like in my case.
FVM should be a seamless wrapper and therefore not add …
=> fix(cosmetics): fvm has one newline too much

scripts/install.sh
```
$ docker run --rm debian:stable uname -m
aarch64
```
it isn't arm64 on linux as far as I can tell (it is arm64 on darwin)
=> fix: unsupported architecture on arm64

lib/src/models/flutter_version_model.dart, lib/src/workflows/ensure_cache.workflow.dart
=> Validate if git is installed

CHANGELOG.md, bin/main.dart, docs/pages/documentation/guides/basic-commands.mdx, lib/src/services/logger_service.dart, lib/src/utils/context.dart, lib/src/utils/context.mapper.dart, lib/src/workflows/ensure_cache.workflow.dart, pubspec.yaml
Fixes https://github.com/leoafarias/fvm/issues/710
=> Add flag to exit with error instead of asking for interaction

lib/src/commands/list_command.dart, pubspec.lock
=> Improved fvm list message

scripts/install.sh, scripts/uninstall.sh, scripts/update.sh
=> feat: automatically add `~/.fvm_flutter/bin` to the PATH var in `install.sh` and introduce `update.sh`

scripts/install.sh
Running the script as root will cause issue as the fvm binary resides in /root
```bash
readlink /usr/local/bin/fvm 
/root/.fvm_flutter/bin/fvm
```
This PR proposes the following changes
- Check if the **script is running as root**.
- Check for the **correct escalation tool** like `sudo` or `doas`.
- Use **escalation inside the script** as symlinking to `/usr` **requires escalated privileges**
- Resolves https://github.com/leoafarias/fvm/issues/796
=> fix: installation bug

docs/pages/documentation/getting-started/installation.mdx, docs/public/install.sh, scripts/README.md, scripts/install.md, scripts/install.sh
Fixes the broken install script URL issue reported in #872 by correcting the documentation to use the working URL `https://fvm.app/install.sh` instead of the broken `https://fvm.app/install`.
In commit a3da7318cdd5f4612f79c37ce0a2d2df4735623f, the documentation was updated to reference `https://fvm.app/install`, but this URL returns a 404 error because:
- ❌ `https://fvm.app/install` returns 404 error
- ✅ `https://fvm.app/install.sh` works correctly
- ❌ Users following official documentation cannot install FVM
Corrected all documentation and script references to use the working URL `https://fvm.app/install.sh`:
- Updated `docs/pages/documentation/getting-started/installation.mdx`
- Updated `scripts/install.sh` (help text and comments)
- Updated `docs/public/install.sh` (to keep in sync)
- …
=> fix: correct install script URLs in documentation (#872)

docs/pages/documentation/getting-started/installation.mdx
Fixes #822 - The Linux tab in the installation documentation was incorrectly displaying macOS Homebrew installation instructions instead of Linux-specific commands.
Replaced the inappropriate Homebrew content with a simple reference to GitHub releases for alternative installation methods, while keeping the install script as the recommended approach.
- ✅ **Removed**: Homebrew installation instructions from Linux tab
- ✅ **Added**: Simple reference to GitHub releases for alternatives
- ✅ **Kept**: Install script as recommended method (already works perfectly for Linux)
This fix follows the project's principles:
- **YAGNI**: Doesn't add unnecessary package manager instructions
- **KISS**: Simple solution that leverages existing working install script
- **DRY**: Avoids duplicating …
=> fix: replace incorrect Homebrew instructions in Linux installation tab

lib/src/services/flutter_service.dart, lib/src/workflows/resolve_project_deps.workflow.dart
- Fix FVM hanging when accessing private repositories during dependency resolution
- Maintain fix for duplicate progress indicators while allowing authentication prompts
- Replace spinner-based progress with simple log messages for cleaner output
FVM was hanging indefinitely when trying to resolve dependencies for projects with private Git repositories. The issue occurred because:
1. `pubGet()` was running with `echoOutput: false` for all operations
2. This prevented stdio inheritance, making authentication prompts invisible
3. The process would wait indefinitely for user input that never came
- Allow stdio inheritance (`echoOutput: true`) for online pub get operations to enable authentication prompts
- Suppress stdio inheritance (`echoOutput: false`) for offline operations to prevent …
=> fix: resolve private repository authentication and duplicate progress indicators

tool/grind.dart
- Enables cli_pkg to generate standalone executables for all platforms
- Adds the necessary configuration for single-file .exe distribution required by WinGet
- Minimal change: adds `pkg.standaloneName.value = _packageName` to grind.dart
Fixes #891 - WinGet requires portable applications to be .exe files, not .bat files. This enables the packaging infrastructure needed for WinGet distribution.
⚠️ **Note**: This change enables the standalone executable configuration, but full functionality depends on upstream cli_pkg support for standalone executables, tracked in [google/dart_cli_pkg#67](https://github.com/google/dart_cli_pkg/issues/67).
**Current situation:**
- The cli_pkg maintainer has been hesitant to add unsigned executable support due to Windows security warnings
- However, recent …
=> feat: enable single-file executable distribution

docs/pages/index.mdx
The GitHub contributors badge is updated to use a more compact style without the "for-the-badge" modifier. This change improves the visual appearance of the badge on the homepage.
=> feat(docs): Update GitHub contributors badge

docs/pages/documentation/getting-started/index.md
The links in the "Next Steps" section of the getting started page have been updated to correctly point to the installation, configuration, and FAQ pages.
=> Docs: Update getting started links

.github/workflows/release.yml
- Removes the problematic `find lib -name "*.mapper.dart" -exec git add {} \;` line from the release workflow
- The .mapper.dart files are already committed and tracked in the repository
- These files should not change during build_runner execution (validated by ensure_build_test.dart)
The release workflow was failing with "find: missing argument to `-exec'` error because:
1. The find command syntax wasn't properly escaped for YAML
2. More importantly, these mapper files don't need to be added during release as they're already committed
Simply remove the line attempting to add .mapper.dart files. The workflow now only commits the actual files that change during release:
- pubspec.yaml (version update)
- lib/src/version.dart (generated version file)
- CHANGELOG.md (release entry)
This fix …
=> fix: remove unnecessary mapper file handling from release workflow

.github/workflows/deploy_docker.yml
- Updated `docker/setup-qemu-action` from v1 to v3 in `deploy_docker.yml`
- Updated `docker/setup-buildx-action` from v1 to v3 in `deploy_docker.yml`
- Aligns with versions already used in `release.yml`
These v1 actions run on deprecated Node.js versions and will eventually stop working. The v3 versions use modern Node.js and prevent deprecation warnings.
=> fix: update Docker action versions to prevent deprecation warnings
